name: "ESPHome for SMHUB"
version: "2026.5.3-1"
slug: "esphome-smhub"
description: "ESPHome builder fork SMLIGHT SMHUB"
url: "https://github.com/smlight-smhub/smhub-addons"
image: "ghcr.io/smlight-smhub/esphome-smhub-{arch}"
startup: "services"
boot: "auto"
arch:
  - amd64
  - aarch64
ingress: true
ingress_port: 6052
panel_icon: "mdi:cube-outline"
panel_title: "ESPHome SMHUB"
host_network: true
privileged:
  - SYS_RAWIO
devices:
  - /dev/bus/usb:/dev/bus/usb
map:
  - ssl:ro
  - config:rw
  - share:rw
options:
  ssl: false
  certfile: "fullchain.pem"
  keyfile: "privkey.pem"
  default_compile_process_limit: 0
schema:
  ssl: bool
  certfile: str
  keyfile: str
  default_compile_process_limit: int?
