name: "ESPHome for SMHUB"
version: "1.0.0"

slug: "esphome-smhub"
description: "ESPHome builder fork SMLIGHT SMHUB"
url: "https://github.com/smlight-smhub/smhub-addons"
image: "ghcr.io/smlight-smhub/esphome-smhub-{arch}"
init: false
startup: "services"
boot: "auto"
arch:
  - amd64
  - aarch64
ingress: true
ingress_port: 0
panel_icon: "mdi:cube-outline"
panel_title: "ESPHome SMHUB"
host_network: true
hassio_api: true
auth_api: true
uart: false
ports:
  6052/tcp: null
map:
  - ssl:ro
  - config:rw
discovery:
  - esphome
backup_exclude:
  - '*/*/'
schema:
  status_use_ping: bool?
  streamer_mode: bool?
  home_assistant_dashboard_integration: bool?
  default_compile_process_limit: int(1,)?
  ssl: bool?
  certfile: str?
  keyfile: str?
  leave_front_door_open: bool?
