packages:
  core: !include common-core.yaml

esphome:
  name: rtos-nano

dashboard_import:
  package_import_url: github://smlight-smhub/smhub-addons/esphome-smhub/nano-esphome.yaml@main

sg2000:
  board: NANO
  version: "2026.5.3"
