esphome:
  name: rtos
  min_version: 2026.5.3
  project:
    name: "smlight.smhub"
    version: "1.0.0"

dashboard_import:
  package_import_url: github://smlight-smhub/smhub-addons/esphome-smhub/smhub-esphome.yaml@main

sg2000:
  board: SMHUB
  version: "2026.5.3"

logger:
  level: DEBUG
  baud_rate: 115200

api:
  reboot_timeout: 0s
  encryption:
    key: "VGVzdGluZ1RSTkdFbmNyeXB0aW9uS2V5MTIzNDU2Nzg="
  services:
    - service: play_rtttl
      variables:
        song_str: string
      then:
        - rtttl.play:
            id: smhub_buzzer
            rtttl: !lambda 'return song_str;'

switch:
  - platform: gpio
    name: "Blue led"
    pin: "led_cus"
    restore_mode: RESTORE_DEFAULT_OFF

binary_sensor:
  - platform: gpio
    name: "User Button"
    pin: 
      number: "btn_2"
      mode:
        input: true
        pullup: true
    filters:
      - delayed_on: 10ms

light:
  - platform: sg2000_ws2812
    id: status_led
    name: "Status LED"
    spi_base: 0x04180000
    num_leds: 12
    effects:
      - pulse:
      - strobe:
      - random:
      - addressable_rainbow:
          name: "Rainbow Effect"
          speed: 10
      - addressable_color_wipe:
          name: "Color Wipe Effect"
      - addressable_scan:
          name: "Scan Effect"
          move_interval: 100ms
          scan_width: 1
      - addressable_fireworks:
          name: "Fireworks Effect"

rtttl:
  output: smhub_pwm
  id: smhub_buzzer

bluetooth_proxy:
  active: true

i2c:
  i2c_id: 4
  frequency: 100kHz

output:
 - platform: sg2000_pwm
   id: smhub_pwm
   pwm_id: 3
   channel: 2

time:
  - platform: smhub_time
    id: smhub_time

ota:
  - platform: esphome
    port: 3232


